import { EventConfig } from "./EventConfig";

export const NextEventConfig: EventConfig = {
  evenements: [
    {
      id:1,
      titre: 'Dedicace',
      agePublic: 'Adultes',
      prix: 20,
      rue: '10 rue de la liberte',
      ville: 'Draguignan',
      codePostal: 83300,
      maxParticipants: 10,
      date: new Date(),
      utilisateurs: [
        { nom: 'user1' },
        { nom: 'user2' },
        { nom: 'user3' },
        { nom: 'user4' },
        { nom: 'user5' },
      ],
      livre: { titre: 'Titre Livre', photo: 'https://picsum.photos/800' },
      auteurs: [
        { nom: 'Auteur 1', photo: 'https://picsum.photos/800' },
        { nom: 'Auteur 2', photo: 'https://picsum.photos/800' },
      ],
    },
    {
      id:2,
      titre: 'Dedicace',
      agePublic: 'Adultes',
      prix: 20,
      rue: '10 rue de la liberte',
      ville: 'Draguignan',
      codePostal: 83300,
      maxParticipants: 10,
      date: new Date(2023, 1, 16),
      utilisateurs: [
        { nom: 'user1' },
        { nom: 'user2' },
        { nom: 'user3' },
        { nom: 'user4' },
        { nom: 'user5' },
        { nom: 'user6' },
        { nom: 'user7' },
        { nom: 'user8' },
        { nom: 'user9' },
        { nom: 'user10' },
      ],
      livre: { titre: 'Titre Livre', photo: 'https://picsum.photos/800' },
      auteurs: [
        { nom: 'Auteur 1', photo: 'https://picsum.photos/800' },
        { nom: 'Auteur 2', photo: 'https://picsum.photos/800' },
      ],
    },
    {
      id:3,
      titre: 'Dedicace de livre',
      agePublic: 'Adultes',
      rue: '10 rue de la liberte',
      ville: 'Nice',
      codePostal: 6200,
      date: new Date(2023, 2, 6),
      utilisateurs: [],
      livre: { titre: 'Titre Livre', photo: 'https://picsum.photos/800' },
      auteurs: [
        { nom: 'Auteur 1', photo: 'https://picsum.photos/800' },
        { nom: 'Auteur 2', photo: 'https://picsum.photos/800' },
      ],
    },
    {
      id:4,
      titre: 'Rencontre auteur',
      agePublic: 'ados',
      rue: '10 rue de la liberte',
      ville: 'Nice',
      codePostal: 6200,
      maxParticipants: 10,
      date: new Date(2023, 1, 19),
      utilisateurs: [
        { nom: 'user1' },
        { nom: 'user2' },
        { nom: 'user3' },
        { nom: 'user4' },
        { nom: 'user5' },
        { nom: 'user5' },
        { nom: 'user5' },
      ],
      livre: { titre: 'Titre Livre', photo: 'https://picsum.photos/800' },
      auteurs: [
        { nom: 'Auteur 1', photo: 'https://picsum.photos/800' },
        { nom: 'Auteur 2', photo: 'https://picsum.photos/800' },
      ],
    },
    {
      id:5,
      titre: 'Seance de dedicace',
      agePublic: 'ados',
      rue: '10 rue de la liberte',
      ville: 'Nice',
      codePostal: 6200,
      date: new Date(2023, 1, 25),
      utilisateurs: [
        { nom: 'user1' },
        { nom: 'user2' },
        { nom: 'user3' },
        { nom: 'user4' },
      ],
      livre: { titre: 'Titre Livre', photo: 'https://picsum.photos/800' },
      auteurs: [
        { nom: 'Auteur 1', photo: 'https://picsum.photos/800' },
        { nom: 'Auteur 2', photo: 'https://picsum.photos/800' },
      ],
    },
    {
      id:6,
      titre: 'Atelier lecture',
      agePublic: 'ados',
      rue: '10 rue de la liberte',
      ville: 'Nice',
      codePostal: 6200,
      date: new Date(2023, 2, 11),
      utilisateurs: [],
      livre: {},
      auteurs: [],
    },
    {
      id:7,
      titre: 'Atelier lecture',
      agePublic: 'adulte',
      rue: '10 rue de la liberte',
      ville: 'Nice',
      codePostal: 6200,
      date: new Date(2023, 1, 28),
      utilisateurs: [
        { nom: 'user1' },
        { nom: 'user2' },
        { nom: 'user3' },
        { nom: 'user4' },
      ],
      livre: {},
      auteurs: [],
    },
  ],
  selectedEvent: [],
  ApiRoute: "/evenements",
  text: "",
  customClass: "custom-date-class",
  isPast: false,
  textTitle: "Prochainement :",
  textTime: "a venir :",
  customColor: 'orange',
}