import { EventConfig } from './EventConfig';

export const PastEventConfig: EventConfig = {
  evenements: [
    {
      titre: 'Dedicace',
      agePublic: 'Adultes',
      prix: 20,
      rue: '10 rue de la liberte',
      ville: 'Draguignan',
      codePostal: 83300,
      maxParticipants: 10,
      date: new Date(2023, 0, 7),
      utilisateurs: [
        { nom: 'user1' },
        { nom: 'user2' },
        { nom: 'user3' },
        { nom: 'user4' },
        { nom: 'user5' },
      ],
      livre: { titre: 'Titre Livre', photo: 'https://picsum.photos/800' },
      auteurs: [
        { nom: 'Auteur 1', photo: 'https://picsum.photos/800' },
        { nom: 'Auteur 2', photo: 'https://picsum.photos/800' },
      ],
    },
    {
      titre: 'Dedicace',
      agePublic: 'Adultes',
      prix: 20,
      rue: '10 rue de la liberte',
      ville: 'Draguignan',
      codePostal: 83300,
      maxParticipants: 10,
      date: new Date(2023, 0, 1),
      utilisateurs: [
        { nom: 'user1' },
        { nom: 'user2' },
        { nom: 'user3' },
        { nom: 'user4' },
        { nom: 'user5' },
      ],
      livre: { titre: 'Titre Livre', photo: 'https://picsum.photos/800' },
      auteurs: [
        { nom: 'Auteur 1', photo: 'https://picsum.photos/800' },
        { nom: 'Auteur 2', photo: 'https://picsum.photos/800' },
      ],
    },
    {
      titre: 'Dedicace de livre',
      agePublic: 'Adultes',
      rue: '10 rue de la liberte',
      ville: 'Nice',
      codePostal: 6200,
      date: new Date(2023, 0, 9),
      utilisateurs: [
        { nom: 'user1' },
        { nom: 'user2' },
        { nom: 'user3' },
        { nom: 'user4' },
        { nom: 'user5' },
      ],
      livre: { titre: 'Titre Livre', photo: 'https://picsum.photos/800' },
      auteurs: [
        { nom: 'Auteur 1', photo: 'https://picsum.photos/800' },
        { nom: 'Auteur 2', photo: 'https://picsum.photos/800' },
      ],
    },
    {
      titre: 'Atelier lecture',
      agePublic: 'ados',
      rue: '10 rue de la liberte',
      ville: 'Nice',
      codePostal: 6200,
      maxParticipants: 10,
      date: new Date(2023, 0, 15),
      utilisateurs: [
        { nom: 'user1' },
        { nom: 'user2' },
        { nom: 'user3' },
        { nom: 'user4' },
        { nom: 'user5' },
        { nom: 'user5' },
        { nom: 'user5' },
      ],
      livre: { titre: 'Titre Livre', photo: 'https://picsum.photos/800' },
      auteurs: [
        { nom: 'Auteur 1', photo: 'https://picsum.photos/800' },
        { nom: 'Auteur 2', photo: 'https://picsum.photos/800' },
      ],
    },
    {
      titre: 'Atelier lecture',
      agePublic: 'ados',
      rue: '10 rue de la liberte',
      ville: 'Nice',
      codePostal: 6200,
      date: new Date(2023, 0, 10),
      utilisateurs: [
        { nom: 'user1' },
        { nom: 'user2' },
        { nom: 'user3' },
        { nom: 'user4' },
        { nom: 'user5' },
      ],
      livre: { titre: 'Titre Livre', photo: 'https://picsum.photos/800' },
      auteurs: [
        { nom: 'Auteur 1', photo: 'https://picsum.photos/800' },
        { nom: 'Auteur 2', photo: 'https://picsum.photos/800' },
      ],
    },
  ],
  selectedEvent: [],
  ApiRoute: '',
  textTitle: 'Précédemment :',
  textTime: 'passés :',
  text: '',
  customClass: 'custom-date-class2',
  isPast: true,
  customColor: 'tomato'
};
